### ISSUE TITLE
Refactor Transfer Interface 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene-ui#134]
Here is a mockup of what I would like the new transfer dialog to look like.   Notice how it reads like a sentence.   It is also laid out to work well on mobile interfaces. 

![image](https://cloud.githubusercontent.com/assets/347290/9063915/f1ac5f94-3a97-11e5-829d-d7a45c02a182.png)

**Comment by svk31** [comment]
The new transfer page does not trigger the unlock modal if the wallet is locked and gives no feedback as to why the transfer doesn't work except for an error in the console.

**Comment by valzav** [comment]
@svk31 I'm going to add unlock capability to transaction confirmation dialog, so let's keep this out of scope transfer screen.

**Comment by jcalfee** [comment]
The ApplicationApi transfer method did something with the memo key.  Because that was already an promise method I was able to easily put in a unlock promise there.  https://github.com/cryptonomex/graphene-ui/commit/68f7e9cb667c083b1adbcdf13a8c523190b2731d

@valzav the unlock event will happen anytime you try to sign a transaction so there is no need to do this in the transaction dialog.
