### ISSUE TITLE
Some assets are not shown in explorer

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#146]
Asset id between 1.3.128 to 1.3.319 is not shown asset explorer. (mostly start with C and D)

**Comment by valzav** [comment]
has anybody looked into this? is this issue still present?

**Comment by svk31** [comment]
Yea it's simply due to the asset lookup api call limiting us to 100 assets at a time, we either need to add some logic to fetch assets alphabetically until we've got them all, or instead we could simply not show all assets and only present the user with a search field and then let them "bookmark" assets if desired for example.
