### ISSUE TITLE
Recent Activity transactions only show one operation

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#154]
It would be nice to see the operations such as balance claims grouped by asset id and totaled.  Currently only one operation is shown and the total in the history does not reflect the total balance claim.

url: http://localhost:8080/#/account/myaccount

**Comment by jcalfee** [comment]
At least show all of them...

**Comment by svk31** [comment]
We can't show all of them atm, only the last 100 cause that's all that's supported by the backend. What's being shown is the last 20 operation, we could of course increase that to 100 but it would crowd out the account overview imo. That's why we used to have a account history page but @valzav removed it.

I do like your idea of sorting by operation type though!

**Comment by jcalfee** [comment]
It is fixed .. Thank you
