### ISSUE TITLE
[Dashboard.jsx] - Linking on cards has 100% height! 

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene-ui#172]
As example .. i'm getting displayed 3 account in one row on my current dashboard!
When move mouse to bottom of screen these 3 acc still are clickable also at bottom line...

Hopefully i was able to explain it understandable ;)

**Comment by svk31** [comment]
Yea this is due to the wrapping div with `style={{alignItems: "flex-start"` being removed in this commit: https://github.com/cryptonomex/graphene-ui/commit/dc2d198a426ce966f781300299cbd8c2b40add5e

The cards now evenly divide the vertical space between them, so one row -> 100% height, 2 rows 50% each etc.

**Comment by valzav** [comment]
I'll return alignItems style back
