### ISSUE TITLE
Error using ChainTypes.ChainAccountsList: "Failed propType: resolvedLinkedAccounts in ComponentTest should be Immutable.List"

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene-ui#214]
I'm converting the linkedAccounts set into a Immutable List below.  I'm not sure why BindToChainState is throwing this error.

``` javascript
@BindToChainState()
export default class ComponentTest extends Component {

    static propTypes = {
        resolvedLinkedAccounts: ChainTypes.ChainAccountsList.isRequired
    }

    static defaultProps = {
        resolvedLinkedAccounts: Immutable.List(AccountStore.getState().linkedAccounts)
    }

    render() {
        return (
            <span>{this.props.resolvedLinkedAccounts.size}</span>
        )
    }

}
```

See `http://localhost:8080/#/test`

**Comment by jcalfee** [comment]
In BindToChainState, a `debugger` shows this appears to be an array object.  It fails the Immutable.List.isList check...

**Comment by jcalfee** [comment]
In BindToChainState, a well placed `debugger` command shows something that appears to be an array object.  It fails the Immutable.List.isList check...

**Comment by valzav** [comment]
I think the problem here is with defaultProps - first of all AccountStore's linkedAccounts might not be ready at the time this class is constructed, try to init resolvedLinkedAccounts in constructor().
Second issue I noticed - for some reason defaultProps' resolvedLinkedAccounts doesn't get Immutable.List value, looks like it gets converted to array of Lists.
My suggestion is to not use defaultProps for Immutable containers.

**Comment by jcalfee** [comment]
The same issue occurs when using the AltContainer and connecting to the AccountStore and instead passing in props for the linkedAccounts.  Here is more sample code.. This is not used, just a template.

https://github.com/cryptonomex/graphene-ui/blob/master/web/app/components/Utility/ChainResolveComponents.jsx
