### ISSUE TITLE
The most recent price label on the market page is misplaced

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#376]
https://bitsharestalk.org/index.php/topic,19417.msg249453.html#msg249453

**Comment by svk31** [comment]
I disagree, that price is the latest price in the market chart which is not necessarily the price of the latest transaction (at least the way the get_market_history api currently works).

That's why I have not used that price to display "Latest price" up top, because I haven't had reliable access to it. BM has now added a basic fill order history that I will use to add the price you want.
