### ISSUE TITLE
My favourite Markets Page should display UIA price

### ISSUE THREAD

**Issue by ghost** [cryptonomex/graphene-ui#388]
https://bitsharestalk.org/index.php/topic,19417.msg249653.html#msg249653

**Comment by liondani** [comment]
#369

**Comment by wmbutler** [comment]
This appears to be resolved. Please close if you agree @sharedworld

**Comment by svk31** [comment]
It's not the case still for some assets since the calculation uses the asset's core exchange rate which may not be set and may also be incorrectly set. This issue should probably be replaced by a new issue to refactor the method used to calculate both equivalent value and current price since they use similar logic. The refactor should make use of an api call to get order history and use the latest price for the market instead of core exchange rate.

**Comment by wmbutler** [comment]
Closing and tracking as #450
