### ISSUE TITLE
The [Market Depth] / [Price Chart] button is unnecessarily highlighted after being clicked

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#392]
https://bitsharestalk.org/index.php/topic,19417.msg249665.html#msg249665

**Comment by neura-sx** [comment]
This refers to OL theme only.

**Comment by wmbutler** [comment]
Agreed, this button should lose focus after being clicked. An even better fix would be to make this a toggle (price chart / market depth). And while we are at it, we could differentiate the BORROW USD button since it has nothing to do with the toggle.

High contrast = active screen so Market Depth would be displayed in this case:

![screen shot 2015-11-05 at 5 30 36 pm](https://cloud.githubusercontent.com/assets/1254810/10983834/1aab961e-83e3-11e5-925e-59b8529cda65.png)

**Comment by c055** [comment]
also referenced on openledger GUI https://github.com/openledger/graphene-ui/issues/8

**Comment by svk31** [comment]
This is no longer an issue as far as I can tell on OL, the buttons lose focus after clicking on them. Also, due to space issues I prefer to not have two buttons for switching between depth/price charts.

**Comment by wmbutler** [comment]
ok, but I still think a toggle makes more sense to give the user a clue as to what their other option is. Closing.
