### ISSUE TITLE
The MORE MARKETS button is too inconspicuous

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene-ui#448]
https://bitsharestalk.org/index.php/topic,19417.msg254149.html#msg254149

**Comment by wmbutler** [comment]
Let's solve a number of issues with this one. We've had requests for a few things related to the Market in the lower right corner of the trade screen. This UX addresses the following:
- The starred markets tab should be the default
- Make sure that only the market line items scroll. The header should stay fixed with the filter box.
- display volume per market
- display price per market
- allow user to jump to the market
- allow user to flip market symbols
- allows user to manage favorites

This screen may take a second to digest
- It's currently on the ALL MARKETS tab
- By default it shows no markets unless a user enters a filter
- The filter shows any contiguous letter matches, case insensitive, as a typeahead so
- BT brings up BTS:USD, USD:BTC, TRADE.BTC:BTC
- The user can elect to either click on the market and jump to it,  star it, or click on the price to swap the pairs. The market pairs should swap as well. I suppose the gain/loss percentage should swap as well.

If the user stars a market, it will appear in the Starred Markets tab.

![screen shot 2015-11-06 at 3 25 29 am](https://cloud.githubusercontent.com/assets/1254810/10993000/627563a2-8439-11e5-953f-8808592d20c6.png)

**Comment by svk31** [comment]
I've implemented large parts of this now, what remains is notably the search functionality, and the "All markets" only uses the already defined markets from the previous "favorite markets" functionality.

![image](https://cloud.githubusercontent.com/assets/6890015/11165497/7c12f82c-8b11-11e5-8f8f-a470a8a91ecb.png)

I have to think some more about how to add "All markets", we can't really show all markets because there are thousands of combinations. I like the idea of having an empty list though that gets populated when you search, but again there are just soo many combinations.

**Comment by svk31** [comment]
OK this should be ready to go now. I still need to refactor the Market cards in the overview, but at least the table view has the new functionality.

I've added some default base options that will show up when searching unless the user specifies a particular base as so USD:BTC. The currrent defaults are BTS, USD, CNY, and BTC.

**Comment by wmbutler** [comment]
I know you've closed this already, but All Markets could be empty until a user starts typing in the search area. Then you wouldn't have to load them all....or you could display the top 20 markets alphabetically if nothing is typed into the search/filter box.

**Comment by svk31** [comment]
No worries, that's how I implemented it finally :)
