### ISSUE TITLE
Market: Clicking on account balance vs Lowest Ask

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#469]
This is strange. I don't know what to make of it, but it could be a javascript floating point issue:

When I click on the underlined balance next to billbutler-dev, the Pay field contains `322.78844`

![screen shot 2015-11-08 at 11 49 30 am](https://cloud.githubusercontent.com/assets/1254810/11021438/217ab4ce-860f-11e5-9dde-a40a5ada688f.png)

When I click on the underlined balance next to Lowest ask, the Pay field contains `322.78049`

![screen shot 2015-11-08 at 11 49 36 am](https://cloud.githubusercontent.com/assets/1254810/11021444/52f36a3c-860f-11e5-8fa1-ecf38b1ff97a.png)

Pretty sure this is an easy fix and I'd place it as high priority since this is a confidence killer.

**Comment by svk31** [comment]
This is not actually a bug but a consequence of how the blockchain assets work, specifically the limited and different precisions. 
Say asset A has precision 2 (max 2 decimals), asset B has precision 5.
I have 5.12555 of asset B that I want to sell for 2 A/B.

With full precision I would receive 2 \* 5.12555 = 10.2511 of asset A. However, that is not possible since the precision of A is 2, so I would need to sell slightly less B in order to receive a maximum of 10.25 A. The max amount I could sell would be 10.25 / 2 = 5.125 B.

So there's a remainder of 0.00055 B that I cannot sell.

What I can do is add a warning in this case, making it more explicit that it is not possible to sell the entire balance at the chosen price.

**Comment by wmbutler** [comment]
So, since this is a shortcut means to enter an order, can you just run the calculation to deal with the exception rather than throwing a warning? I can't thing of a case where a user wants to be presented with an error.

**Comment by svk31** [comment]
Yes, I can calculate the max amount one can sell at the given price, and use that as the total instead of the actual balance. I suspect users will still find it confusing however that upon clicking their balance, the whole amount is not used in the transaction.

**Comment by wmbutler** [comment]
This leads to the issue of needing to deduct out fees right? I think that in order to make this flow properly, you should have a line item for the fee and extract the fee as well. Would this provide a clear consistent feedback loop?

**Comment by svk31** [comment]
Yes the fee should be taken into account as well, I've been meaning to add the fee anyway. Mind making a mockup of how the fee should be presented? Below the total? Below? Line separators? etc

**Comment by wmbutler** [comment]
Yes, I'll mock this up and move to 1118

**Comment by wmbutler** [comment]
Moving this to 1125 and UXing it soon.

**Comment by wmbutler** [comment]
OK, @svk31 here is the UX for the fee.
- Also, include a warning prior to trade execution if use does not have enough BTS to cover fee
- Disable Buy/Sell button if insufficient BTS to cover fee

![screen shot 2015-11-21 at 9 22 07 pm](https://cloud.githubusercontent.com/assets/1254810/11321641/fbc5b4cc-9095-11e5-9cca-481ac4e59c3f.png)

**Comment by svk31** [comment]
I'd appreciate some testing of this, it's pretty complicated handling different edge cases here so I might have missed something.. I'm using a notification to tell the user he doesn't have enough funds to pay the fees since it was the fastest way, I can go back later if we really want it in the Fee field.

**Comment by wmbutler** [comment]
Ultimately, we will want it in the fee field, but this is a major improvement.
