### ISSUE TITLE
Cease IE support and warn IE users that they need to switch to Edge, Chrome or Firefox

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#474]

**Comment by wmbutler** [comment]
![screen shot 2015-11-09 at 8 16 59 pm](https://cloud.githubusercontent.com/assets/1254810/11051860/f5397d7e-8720-11e5-99e2-e12e1e55f754.png)

**Comment by valzav** [comment]
I think we can IE 11 support - some of the calls can be replaced with workarounds.
But for IE < 11 we have to show a warning like this.

**Comment by wmbutler** [comment]
We should default to displaying incompatible for any version that has already been verified to not work and simply add to the exception list as cases are revealed. Think that's possible? The hardest part of this is the UX since browser detection should be quick. I think this should remain open until the warning is in place.

**Comment by wmbutler** [comment]
Display unsupported browser for :+1: 
- IE
- Firefox

We can bring back support later as we are able to focus on edge cases. Chrome is the official browser for now.

**Comment by wmbutler** [comment]
Wording:

The Browser you are using has not been fully tested to support the Bitshares Wallet. We highly recommend that you backup your wallet and import it using the Chrome Browser until we have had more time to fully test your browser of choice. Use at your own risk.
