### ISSUE TITLE
Missing Balance

### ISSUE THREAD

**Issue by RenaudGagne** [cryptonomex/graphene-ui#476]
Hi, 

I download 0.9.3c and imported my keys from the previous version into it. Since there is no delegate there is no network connection. When I export and import they keys into bitshares 2.0, here is the message I get: 

Unclaimed balances belonging to these keys:
ASSET TOTALS
18,220.35302 BTS

I am supposed to have much more in there.

**Comment by wmbutler** [comment]
@RenaudGagne This is not really a function of the graphene-ui. It's possible that you have transactions that need to be synchronized in the 0.9.3c wallet. This can be painstakingly slow, but it is necessary. Alternatively, if you ever had another wallet, make sure you didn't have balances associated with it. I am closing the issue here since it's not something that the ui developers have any control over.

I would suggest that you post this in BitsharesTalk under the Questions section. Most importantly, get your 0.9.3c fully synced and then backup your wallet.
