### ISSUE TITLE
Does not build with the latest Node on Windows

### ISSUE THREAD

**Issue by ByronAP** [cryptonomex/graphene-ui#481]
Does not build with the latest Node on Windows. Throws a ton of errors while installing deps and during build.

**Comment by wmbutler** [comment]
What is the recommended node version @valzav ?

**Comment by svk31** [comment]
0.12.7 is the version we've been using. Newer versions of NPM (that come with node) do not install peer dependencies and because of this the installations fail due to missing dependencies. I can have a look and update the dependencies, but until then you can simply install the ones npm complains about manually.

**Comment by wmbutler** [comment]
Do we really need latest node? I'd suggest staying on 0.12.7 since we have bigger fish to fry. @ByronAP will you close this and we can look at it in a month or so?

**Comment by ByronAP** [comment]
Yes, can we just note the instructions with the proper version and deps. So people are not scrambling to piece things together.

On Wed, Nov 18, 2015 at 4:30 AM -0800, "Bill Butler" <notifications@github.com<mailto:notifications@github.com>> wrote:

Do we really need latest node? I'd suggest staying on 0.12.7 since we have bigger fish to fry. @ByronAPhttps://github.com/ByronAP will you close this and we can look at it in a month or so?

##

**Comment by wmbutler** [comment]
@ByronAP would you like to fork and propose propose those instructions yourself? I'll close this.
