### ISSUE TITLE
Market %change and volume do not match

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#528]
![screen shot 2015-11-23 at 8 10 35 pm](https://cloud.githubusercontent.com/assets/1254810/11354935/731860ae-921e-11e5-80e5-a8f7a6039821.png)
![screen shot 2015-11-23 at 8 10 28 pm](https://cloud.githubusercontent.com/assets/1254810/11354936/7323f446-921e-11e5-8c93-3ce411e40ef9.png)

**Comment by noisy** [comment]
I think, values are correct, at least in my wallet. Once is for USD:BTS, second is BTS:USD.

![selection_001](https://cloud.githubusercontent.com/assets/201263/11355023/ae3d585a-9251-11e5-872c-bfef2a654893.png)

However I see from you screenshots, that you have different values for this same pair, right?

**Comment by svk31** [comment]
Yes they're correct, simply inversed. Going from 10 to 20 is a 100% increase, while the inverse, going from 0.1 to 0.05, is a 50% decrease.

**Comment by svk31** [comment]
Oh looking more closely at your pictures I see there's something strange, but it might be due to the two being out of sync. They have different refresh cycles, the status bar values will always be in sync with the market but the market list ones might fall out of sync (but I recently added a 2 minute refresh cycle for them).

I've had  a quick look on my end and the values are all the same for me.
