### ISSUE TITLE
Price Chart Layout Suggestion

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#538]
Problem: Upper information (T, OHLC, V) and bottom volume chart is too big.
Suggestions: 
1. Adjust the ratio of price chart to volume chart to 3.5 : 1
2. Locate 1d ~ 15s buttons next to 24h change
3. Put indicator button left to Market Depth button
4. Arrange T, OHLC, and V in a line

I think Bitcoinwisdom is an examplar.

https://bitcoinwisdom.com/markets/bitfinex/btcusd
https://tradeblock.com/markets/bfnx/xbt-usd/2h/

**Comment by clayop** [comment]
![chart](https://cloud.githubusercontent.com/assets/9971632/11415394/190565a4-93b7-11e5-9f87-dae9be4d220b.jpg)

**Comment by clayop** [comment]
Add: Can the volume chart be one of the indicators? (meaning that users can on/off the volume chart. But the default is on)

**Comment by svk31** [comment]
Edit: I don't think I'll put the tooltip in a line, it causes issues with readability and text jumping due to different amount of integers. Same for the indicator button/bucket size selector , they can't go up there because there's no space. In some cases you'll have two borrow buttons and a small screen, I already had to move the account selector due to lack of space.

I can make the volume charts part of the indicators though, and I can make them smaller.

**Comment by wmbutler** [comment]
@svk31 I have a whole UX for this page. Should I post it here? It basically makes this page cleaner with the same functionality. I modeled largely on the BitcoinWisdom page because I personally love how things are displayed there.

**Comment by wmbutler** [comment]
There is a lot going on here, but I think this UX introduces a few things that end users will appreciate (I lifted much of this design from bitcoinwisdom).
- [ ] Display the time intervals all the time rather than hiding them behind a gear (chosen range is in blue)
- [ ] Draw thin grey borders to visualize logical separators and structure. Our current design, while functional, feels a little loose.
- [ ] Box in the trading pair in upper left corner
- [ ] Box in all values currently displayed on existing client
- [ ] Display all currency/trading pairs in blue hilight color
- [ ] Added symbol name to buy or sell button. "BUY USD"
- [ ] Flattened the look of the My History and My Markets to fit overall look. In particular, I remove the white line at the top of each and note the contrast of the inactive tab discussed in issue #527 
- [ ] ~~Use same shade of red and green throughout (I didn't UX this but I think it's important.~~
- [ ] Display stats for cursor hover as one line in upper left (make sure chart has padding so it will not encroach on this.
- [ ] BUY ASSET displayed in large typeface above the buy and sell areas (this will give the user a better indicator of what they are buying and selling. Also changed labels. This is how Poloniex has things displayed and it feels very clear.
- [ ] Note the settings dropdown ala Bitstamp. I showed all the technical indicators for example, but you could simply display the technical indicators that you've created so far. It would be a bit lighter weight than the modal you have for this now.

![screen shot 2015-11-28 at 6 01 54 am](https://cloud.githubusercontent.com/assets/1254810/11451475/b9ff1236-9595-11e5-9dc4-0604d4c00217.png)

**Comment by clayop** [comment]
This is great and much better than my coarse one!
But you might miss the "indicator" button next to time interval. :)

**Comment by svk31** [comment]
Me like. One thing though: the colors should not imo be the same everywhere, although I realize the current implementation isn't correct really either. If you go to bitcoinwisdom you'll notice they also have two shades of red and two green: one pair for up/down; one for ask/bid. In the order history it should be ask/bid color, while the chart should have up/down colors, as should the volume/price change and latest price. 

I used to have the symbols in the buy/sell buttons, not sure when they got removed tbh, must've been by accident.

I also like the borders, I've wanted to make it like that for a while really.

One issue I see is the statusbar up top: if this were the BTC:USD market instead you'd have two Borrow buttons and run out of space even at the width you're showing, and lots of users have tiny screens..

**Comment by clayop** [comment]
For color shades, can we copy Bitcoinwisdom's color scheme? Their layout looks great and very legible.

**Comment by wmbutler** [comment]
Updated this UX @svk31

**Comment by svk31** [comment]
I had to make some compromises due to lack of space, and it's not quite done yet, but the preliminary result is not too bad I think:

![image](https://cloud.githubusercontent.com/assets/6890015/11483806/d45e45b8-97aa-11e5-836a-ef2c104b7f65.png)

**Comment by wmbutler** [comment]
Looks great! Look at my design for market depth toggle and Borrow. I guess I don't understand why that wouldn't work? Great work though. @svk31

**Comment by wmbutler** [comment]
Also, note the label changes below BUY BTS as well. I made these changes specifically mirroring poloniex since this seems to be a very well-received trading platform.
- Buy becomes Amount
- Pay becomes Total

Those labels are the same on the sell side as well.

**Comment by clayop** [comment]
@svk31 Is this layout support 8-decimal assets? It looks to have no space for additional decimals.
How about placing Borrow and Market Depth button in the same line with Settings?

**Comment by svk31** [comment]
I'm not sure how your design was any different wmbutler, looks to me it only removed the button style? Anyway I've made some more adjustments, I liked to clayop's suggestion so I went with that, but pushed to the right always. I've also added the text changes that I missed, and some hover states. I've also changed the pricechart colors, they use the same colors as the up/down changes, but it definitely looks different. I played with the alpha a little to make it look more alike but still something fishy with those colors. Anyway: final version with 8 decimal asset:

![image](https://cloud.githubusercontent.com/assets/6890015/11509260/6e148660-985d-11e5-9bed-344e3cee5fd9.png)

I might come back and do the Settings into a dropdown a little later.

**Comment by wmbutler** [comment]
It all looks pretty awesome to me. 
- You could remove the star from My Markets as well. It would match My History then.
- I noticed you didn't add a horizontal separator between candlesticks and volume. I like the separation to help users see the difference in the number scale on the right.
- I also had a horizontal separator at the base of the volume indicators, once again I just think it creates a nice squaring effect.

**Comment by svk31** [comment]
Yea, unfortunately Highcharts isn't very flexible when it comes to lines and borders, it's a bit all or nothing. I'll take the star out though.

**Comment by clayop** [comment]
Sorry for adding comment after closing it.
1. Can we unite the buy color to new green one? I see characters in history and order book have different green (tortoise?) color.
2. The second row on the top (where time interval is located) should have the same height as the above one. Can we reduce the second row's height? (increasing the first row may waste space)
3. Vertical order book should fit in a screen. Why don't you limit the number of orders (in the vertical order book only) and make it fit to the screen? This naturally resolve centering issue of the latest price.

**Comment by clayop** [comment]
![image](https://cloud.githubusercontent.com/assets/9971632/11510640/8bc011be-9819-11e5-8876-b812ca0590fa.png)

Regarding 3, please see my screenshot.

**Comment by svk31** [comment]
1. Like I said in an earlier comment the colors are different for a reason, in the depth chart, buy/sell buttons, orderbook and history they indicate ask/bid/call (order type). In the price chart and volume/price movements they indicate up/down.
2. I tried before your comment, result: I hate CSS.. 
3. I did include a fix for the centering yesterday so it stays centered when you click around markets for example. I like including more orders, although they do already get filtered to not include everything. Filtering to include exactly enough is complicated since you need to start listening to vertical changes as well as monitor orderbook changes and recalculate everything all the time.
