### ISSUE TITLE
Disable 'Force settlement' button in the UI when there are buy orders above feed

### ISSUE THREAD

**Issue by mindphlux1** [cryptonomex/graphene-ui#560]
There has been an active committee proposal to temporarily disable the force settlement function, see here:

https://bitsharestalk.org/index.php/topic,20299.0.html

The Chinese community feels threatened by this because it appears they didn't know about this feature (blame it on the language barrier), and hence this compromise was created to give them one week breathing time to implement a liquidity bot to make sure there are always buy orders above feed price.

Task:

Disable the 'Settle' button when there are buy orders above feed price, preventing users from intentionally abusing the function to 'hurt' shorters when there are in fact buy orders available. Maybe instead, it should buy from the market itself?

**Comment by wmbutler** [comment]
Seems like buying from the market makes sense, however in the interest of time it might be easier to just disable it. I don't have an opinion on this issue because I do not fully understand it, but I'm not particularly interested in alienating any group either. I did read the thread and it still doesn't make a lot of sense to me.

I UX'd the concept of buy/sell bitshares a while ago because I think it fundamentally make more sense to an end user. In coinbase, for instance, a user can buy btc at a rate they set with a 1% fee. This makes it easy to get into BTC without haveing to formally execute a trade.

**Comment by wmbutler** [comment]
@svk31 Mindphlux asked asked us to commit to this one for version 1209. I'm placing it at the top of the list for that.

**Comment by jonnybitcoin** [comment]
So this will be reversed on  Wednesday, December 9th and forced settlement will return to all smart coins?

**Comment by mindphlux1** [comment]
We're expecting to test xeroc's adjusted price script tomorrow and get it adopted among the majority of the witnesses and will probably create the proposal much sooner than Sunday.

**Comment by wmbutler** [comment]
It's up to @svk31 @mindphlux1 you requested it for 1209. Are you requesting 1202 now instead?

**Comment by mindphlux1** [comment]
Please hold off for now until we know the results of the pricefeed test tomorrow.

**Comment by jonnybitcoin** [comment]
So this new feature that disables force settlement. It should leave the force settle button there but prompt user saying you can sell on the open market for more.

**Comment by mindphlux1** [comment]
Closing this since this is no longer needed.
