### ISSUE TITLE
Trading numbers display

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#566]
@svk31 I don't what to overreact here, but this looks like a pretty important issue to address. I hope you agree and will work on this as part of 1202.

```
get_limit_orders "BTC" "TRADE.BTC" 1
[{
    "id": "1.7.4951",
    "expiration": "2020-11-16T16:38:11",
    "seller": "1.2.282",
    "for_sale": 237500,
    "sell_price": {
      "base": {
        "amount": 89999999,
        "asset_id": "1.3.103"
      },
      "quote": {
        "amount": 94736842,
        "asset_id": "1.3.350"
      }
    }
  },{
    "id": "1.7.8303",
    "expiration": "2020-11-30T21:30:30",
    "seller": "1.2.21594",
    "for_sale": 50000000,
    "sell_price": {
      "base": {
        "amount": 50000000,
        "asset_id": "1.3.350"
      },
      "quote": {
        "amount": 50000000,
        "asset_id": "1.3.103"
      }
    }
  }
]
```

Note the first transaction:

```
      "quote": {
        "amount": 94736842,
        "asset_id": "1.3.350"
      }
```

The second transaction is fine, but it has round numbers...

But on the GUI:

![screen shot 2015-11-30 at 6 45 48 pm](https://cloud.githubusercontent.com/assets/1254810/11488183/9b5a30a0-9792-11e5-91aa-b7ee193cb18c.png)

**Comment by svk31** [comment]
The quote amount is not the price, the price is:

price = (base amount \* base precision) / (quote amount \* quote precision)
price = 89999999 / 94736842 = 0,9499999905

(Simplified in this case because the precisions of the two assets are the same so I left that out of the equation)

You cannot easily look at an order object and get the price, you have to do additional calculations.
