### ISSUE TITLE
My History / History alignment

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#568]
I think this is only present on the web client, but the list items should be right aligned with the headers here. (At least for Amount and Value)

![screen shot 2015-12-01 at 1 49 35 pm](https://cloud.githubusercontent.com/assets/1254810/11510589/6c281784-9832-11e5-9bcb-001d2f4ac648.png)

**Comment by svk31** [comment]
It's because the header is in a different table from the the rest to enable scrolling while keeping the header fixed. It's pretty much impossible to get this right imo so I'd prefer to just leave it like that instead of spending lots of time trying to get it right. One solution could be to add a library for this but again it will be a lot of work for very little gain..

**Comment by wmbutler** [comment]
Moving to a late January date.

**Comment by svk31** [comment]
This was actually fixed in a unrelated commit, the actual reason was the show-for-x foundation utility class, I removed that so this is no longer an issue.
