### ISSUE TITLE
Consistent Color Tone

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#577]
Currently three colors categories (green, red, and tortoise(blue)) are used. We need to have consistency in color tone. Maybe needs @cassiopaia 's input.

I personally prefer imitating bitcoinwisdom's color concept. (red/green in chart, and pale red and pale green in buy/sell orders)

**Comment by c055** [comment]
Yep.. Currently all chart stuff colors are directly included into the javascript files .. but after we would have export them to scss or somthing kinda .. i don't see any problems to get them consistent

**Comment by wmbutler** [comment]
@svk31 has articulated this quite a bit. I like consistency in the shades of red and green as well.

**Comment by svk31** [comment]
I'm fine with keeping things more consistent, I do find the turquoise more and more jarring tbh. Not a color guy though so happy to leave that up to cass or wmbutler. Colors for the pricechart are defined in PriceChart.jsx since they have to be in js for highcharts, but I'd appreciate it if you played around with the colors there directly instead of doing mockups because it's hard to get them right in Highcharts.

```
        let positiveColor = "rgba(110, 193, 5, 0.80)";
        let negativeColor = "rgba(225, 66, 74, 0.80)";
```

The others are in exchange.scss

**Comment by wmbutler** [comment]
@cassiopaia Since you are working on the inverted color scheme as well, do you want to take it?

**Comment by c055** [comment]
yep .. i will  go over!

**Comment by wmbutler** [comment]
@cassiopaia placing this in 0106

**Comment by wmbutler** [comment]
@cassiopaia any progress on this?

**Comment by c055** [comment]
nope .. i've to wait till my worker is approved or not .. i can't contribute voluntary or per equity basis anymore .. sry!

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#25
