### ISSUE TITLE
Decimal Bug in Matching in 8-digit Assets

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#586]
I haven't clearly identified yet but from my observation there are some weird cases that maybe caused by decimal error, especially in 8-digit markets. e.g. BTS:TRADE.BTC, BTS:GOLD. I will dig into it when possible.

**Comment by clayop** [comment]
Here's one example. Ordered at 1.03000000 but the confirmation page shows 1.02999999.

![image](https://cloud.githubusercontent.com/assets/9971632/11610655/0631828c-9b5f-11e5-9261-474ce93c9320.png)

**Comment by wmbutler** [comment]
High priority. We need to keep squashing anything related to floating point js issues as the highest priority. As a financial platform, it's the single most important thing.

**Comment by svk31** [comment]
The above commit fixes this particular issue, but you can still get a slightly different price in the confirm dialog than what you entered if you're using maximum precision amounts. I think this is inevitable, since a price in Graphene is not a price in the regular sense of the term, but a ratio amount to sell and amount to buy. 

If the precision is X and Y is 2, and you want to buy 2 X at a price of 1.3455 Y / X, that should cost you 2.691 Y. However, you can only actually use 2.69 Y, so instead the price to buy 2.5 X will be 1.345 Y/X. As far as I can tell that's just the way it has to be in graphene. This also applies to #597

**Comment by svk31** [comment]
@bytemaster do you have an opinion on this? Is there way for us to handle prices that will give consistent and "as expected" prices?

**Comment by xeroc** [comment]
Since prices in graphene are modelled as ratios, we could maybe add a new _class_ to represent prices in the GUI and use numerator `a` and de-numerator `b` and put those in the background of each price and display the price as `p = a/b`.

Then when someone clicks an open order, we could use `a` and `b` directly to create a new order instead of using `p` (which is the source of the issue from what I understand)

**Comment by svk31** [comment]
That's the way it's already handled, for example when someone enters a price manually I calculate an integer ratio to represent that decimal value. Orders taken from the orderbook by clicking on it use the price ratio as given by the blockchain.

The problems arise when combining that price with the amount/quantity the user wants to buy or sell. In some cases this results in a "price" that isn't possible to maintain as described above. There might be a simple solution to this that I'm just not seeing though, probably been staring at it too long..

**Comment by xeroc** [comment]
Assuming that when someone clicks an existing order he wants that particular price, I would only let them change amount/quantity of base or quote and have the other be derived such that the precision of it is ok. At the end of the day an order only contains
- a price (as two integers)
- an amount in either base or quote

So I would recommend to have 4 modes of how a user can input an order:
- match a single open order completely (copy paste of the open order into a new order on the other side)
- open order price with modified base amount (let the user not change the quote amount)
- open order price with modified quote amount (let the user not change the base amount)
- manual everything

Would that work?

**Comment by svk31** [comment]
Should be fixed now with the market update.
