### ISSUE TITLE
These trades should match

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene-ui#597]
@svk31 according to the UI, these trade on BTS:TRADE.BTC should match up. Can you take a look at the precision display here and try to resolve it? These are the types of things that traders shake their heads at.

![screen shot 2015-12-08 at 8 13 13 am](https://cloud.githubusercontent.com/assets/1254810/11656519/c5c1332e-9d83-11e5-8947-fe2d5681e688.png)

**Comment by wmbutler** [comment]
Here is a look at the actual values...how to we deal with this? Are we forced to display the absolute precision here? My gut tells me yes, but I don't know how to fir it all on the screen.

![screen shot 2015-12-08 at 8 16 47 am](https://cloud.githubusercontent.com/assets/1254810/11656579/2b19fe04-9d84-11e5-9bcd-75ef951c660c.png)

**Comment by svk31** [comment]
That isn't actually the real price, it's what I've called "displayPrice" in the code. The actual price is implemented as an integer ratio, something like 123123 / 90909232 (random numbers). I keep prices like that everywhere, but when calling the api in order to submit the order I need to do some more math because you need to specify "amount to sell, amount to buy", not "price and amount". So there might be some floating point issues at that point which I could verify.

In this case it's not a matching issue but simply a decimal one, I guess we need to up the number of decimals to display in general, it's hard to get right really.

**Comment by wmbutler** [comment]
Yeah, I understand how difficult this is, but it's such an important problem to solve, I think it's worth it to deprioritize other items and lock this in.

**Comment by wmbutler** [comment]
It's possible that a user would enter an order manually, looking at one he/she expects to match. When it doesn't match, they would be surprised (but it's really just because we didn't display the full precision of the open orders. Scientific notation might make sense for these extremely small decimals. It's easier than counting the zeros for sure.

`990.34345435 [-5]`

**Comment by clayop** [comment]
IMHO, first, GUI should show only limited number of digits (e.g. 8 digits in this example).
Second, in GUI, price should comes first, and the amount comes second. Lastly, total should be determined. In the example, 0.00000990 BTC/BTS -> 20200 BTS -> 0.19998 BTC, or 0.00000990 BTC/BTS -> 109 BTS -> 0.0010791 BTC.
This may leave some dusts, it's common thing in other exchanges too.
