### ISSUE TITLE
ANTSHARE:TCNY market doesn't show my order in market order list

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#620]
Screenshot attached. It also doesn't show in OpenLedger. 
![trade-gui](https://cloud.githubusercontent.com/assets/9946777/11918807/39afda5e-a740-11e5-9949-45e8f4aa39e8.png)

It's included in the depth chart.

It also appears in CLI wallet. 

```
unlocked >>> get_limit_orders TCNY ANTSHARE 100
get_limit_orders TCNY ANTSHARE 100
[{
...
  },{
    "id": "1.7.14154",
...
}]
```

**Comment by svk31** [comment]
Orders that are too far away from the current highest/lowest bid/ask are filtered out of the orderbook, it's because in some markets you have orders at say a price of 10000000000000 when the actual going rate is 10. This makes the orderbook look ridiculous so I removed them. The cutoff is arbitrary but currently set to 5x lowest ask; 1/5 highest bid. I could increase it slightly if that's desired.

**Comment by abitmore** [comment]
OK. This feature sounds reasonable for me. Maybe document this somewhere? Maybe a "show more" button when something is hidden?
