### ISSUE TITLE
Endless loading with ws://127.0.0.1:8090 on web wallet

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene-ui#638]
In OpenLedger wallet, changing to 127.0.0.1:8090 gives an endless loading error.
It should be loaded or if it's wrong behavior, changing to 127.0.0.1:8090 should be impossible.

**Comment by abitmore** [comment]
127.0.0.1:8090 should have been removed as a solution for #444

**Comment by svk31** [comment]
It was removed so clayop must have added it himself. This issue is different though, it's because using an insecure (ws) websocket is not allowed by the browser from a secure domain like https://bitshares.openledger.info.

I'll make sure we enforce a wss url from secure domains, that way you'll end up on the init error page if the api you enter is incorrect.
