### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bitsacer** [cryptonomex/graphene-ui#645]
Turkish  Light Wallet, on Issued Assets , Update Asset , broken link , page becomes unresponsive after clicking "Update Asset" box.

**Comment by svk31** [comment]
could you please specify the account and asset so I can try to reproduce it?

**Comment by bitsacer** [comment]
ok,  try account name: blok-zinciri , asset : ORBIT ,  the wallet's language needs to be set to turkish though..

**Comment by svk31** [comment]
It's because there are sections missing from the help content files:

![image](https://cloud.githubusercontent.com/assets/6890015/12065054/e951c4c0-afd0-11e5-87f6-c1b5aa22823a.png)

I've modified the HelpContent.jsx component to not throw errors and instead log the error to the console and render nothing, that way it won't crash the entire GUI if it's missing some content.
