### ISSUE TITLE
New registered account is incorrectly set voting proxy to committee-account

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene-ui#700]
See https://github.com/cryptonomex/graphene/issues/543 for cross reference.

> I recently registered an account in GUI (light wallet), paid by another account of mine, not the faucet. See block 3037290 https://cryptofresh.com/b/3037290. Here is part of the transaction
> 
> ```
> ...
>             "options": {
>               "memo_key": "BTS7QC3vSne149XtLGnw6KicvU63ztk2Z7eWbdadMQE54N5FLzR6x",
>               "voting_account": "1.2.0",
>               "num_witness": 0,
>               "num_committee": 0,
>               "votes": [],
>               "extensions": []
>             },
> ...
> ```
> 
> Obviously the `voting_account` in the transaction is incorrectly set to `1.2.0` aka `committee-account`.

**Comment by theoreticalbts** [comment]
The GUI should register new accounts with `GRAPHENE_PROXY_TO_SELF` as `voting_account`.  The `voting_account` should also be set to `GRAPHENE_PROXY_TO_SELF`.

The `GRAPHENE_PROXY_TO_SELF` value is a sentinel value which tells the blockchain to use the account's own ID as its voting proxy (so it can control its own votes).  It's necessary because when registering an account, you don't know what ID it will be assigned.

**Comment by svk31** [comment]
It was indeed using 1.2.0, I've changed it to 1.2.5, guess that should do it?

**Comment by theoreticalbts** [comment]
Probably the sanest thing for the UI to do is reset the user's proxy to `GRAPHENE_PROXY_TO_SELF` whenever they update their votes.  This has the effect of (over time as people update their votes) correcting any accounts which have already incorrectly set `GRAPHENE_COMMITTEE_ACCOUNT` as their proxy.

It doesn't really make sense for the user to update his votes, but then have the updated vote be ineffective because he's using a proxy.  So it's reasonable to assume that if the user's updating his votes, he also wants to revoke any proxy he set in the past.

When the proxy is set to `GRAPHENE_PROXY_TO_SELF`, you might want to have special UI text / graphics indicating the user isn't using a proxy, instead of pretending their proxy is this special system account (which is a low-level implementation detail).

**Comment by theoreticalbts** [comment]
And to answer @svk31 question directly:

> It was indeed using 1.2.0, I've changed it to 1.2.5, guess that should do it?

Yes, new accounts should be registered with `voting_account = GRAPHENE_PROXY_TO_SELF_ACCOUNT`.  But as stated in the previous post, we also need to consider how accounts which were created with this bug should be fixed.

**Comment by abitmore** [comment]
New account in testnet still set to incorrect proxy, see http://testnet.bitshares.eu/#/account/level2-3/voting/
@xeroc @svk31 please check?
