### ISSUE TITLE
Depth chart is not drawn from all data. Orders disappears from "my asks" sections without information

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#711]
It was difficult for me to describe it, so... I recorded a video with that problem - https://youtu.be/BjJUR2Kozn4.

I used testnet to show a problem. (PS. thanks @xeroc for testnet!!!)

**Comment by noisy** [comment]
This issue can be related: https://github.com/cryptonomex/graphene-ui/issues/396

**Comment by svk31** [comment]
Thanks for taking the time to make the video!

However, there's no filtering of data in the graph, and I can't reproduce the error that you got myself, orders get added just fine.

There's some filtering of orders in the orderbook, but it's of orders that are far outside the current trading range that were distorting the orderbook due to having too many characters, numbers like 10223222222222... This only impacts the orders being displayed, not the chart.
