### ISSUE TITLE
On Voting/Workers page it's not obvious that changes take no effect until published

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene-ui#718]
So maybe after Approve button is pressed, it needs to say something like "Supported (publish to cast your vote)" in the status field?

**Comment by abitmore** [comment]
And best if we have a warning before user leave the page, if some changes made but not published.

**Comment by abitmore** [comment]
And/Or maybe just pop up the confirmation window.

**Comment by dnotestein** [comment]
Requiring the user to either publish or cancel pending changes before they leave the page (as I think abit is suggesting) sounds like a reasonable idea. As I understand current operation, it doesn't immediately pop up a confirm when you press the button so that you can "batch" several votes into one transaction.

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#38
