### ISSUE TITLE
Market orders table headers and values do not fit good

### ISSUE THREAD

**Issue by btswolf** [cryptonomex/graphene-ui#720]
The market orders tables ASKS and BIDS do not seem to align perfectly with the underlying columns and values.
![image](https://cloud.githubusercontent.com/assets/11035520/12860222/85102360-cc5b-11e5-9544-028aa58881b3.png)

**Comment by svk31** [comment]
The reason they don't align perfectly is that they're in two separate tables in order to allow the rows to scroll independently of the headers. For some reason this is very difficult to achieve in html, so it would take a lot of work to get perfect. I've made some adjustments though so they're better now.
