### ISSUE TITLE
enable this simple trollbox in the wallet

### ISSUE THREAD

**Issue by btswolf** [cryptonomex/graphene-ui#725]
enable another column on the right side or at the bottom of the wallet with this code embedded.

`<div id="tlkio" data-channel="bitshares-trollbox" style="width:100%;height:400px;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>`

Make it so that users can enable/disable it at will.
Maybe support other chat solutions too but to start this one should be great.

Demo: http://www.btswolf.com/bitshares/
sample: 
![image](https://cloud.githubusercontent.com/assets/11035520/12874052/cae39878-cdcc-11e5-91f0-4a7374461faf.png)

**Comment by btswolf** [comment]
Can we execute this code in a bubble for security reasons?

**Comment by svk31** [comment]
I don't think we should use this because any solution we choose should be open-source. I also prefer to have mod capabilities like in a IRC chat-room.

While I have a basic chatroom implemented already I'm still investigating which library and stack to use, turns out finding a light-weight IRC/XMPP js library is not easy..

**Comment by btswolf** [comment]
I think mod capabilities are only needed if users can`t hide specific accounts.
However I can`t wait to see with what and when you come up with this important feature.
