### ISSUE TITLE
I want to have dates not useless information about blocknumber in my history!

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene-ui#755]
I am not a robot. As a user I prefer to you see and use well formmated dates like 03/03 02:51:12, rather than seeing a useless information about block number.

![selection_165](https://cloud.githubusercontent.com/assets/201263/13483427/879d8336-e0f4-11e5-83de-3942bccf1b11.png)

The interesting part is... that this is not only wrong.. but this is not even a consistent:

`All History` has good date:
![selection_166](https://cloud.githubusercontent.com/assets/201263/13483503/1ba084b6-e0f5-11e5-86dc-6f6bd1f383eb.png)

**Comment by svk31** [comment]
There's a simple reason for this: the date is not available in the data from the api but the block number is. We have a component that calculates the date from the block number, but I tested it here and it's inaccurate due to missed blocks, so you end up displaying a date that could be several days off.

I could instead display a date like "4 months ago", which means the accuracy becomes less of an issue. You can then click on the date to see the block where the transaction happened, which does include the actual date. Would that be acceptable?

**Comment by abitmore** [comment]
@svk31 Can you call `get_block` API to fetch the real timestamp?

**Comment by abitmore** [comment]
By the way on my laptop the timestamp in all history always shows as format "yyyy/m" but not "m/d" or "d/m", very strange. Win7 64bit. Default language in my laptop is set to Simplified Chinese. BitShares GUI language is English. Default date format of my laptop is "yyyy/m/d" (which shows in the system tray).

```
420.00001428    0.23809523  100.0000    2016/3 02:51:12
```

**Comment by abitmore** [comment]
And the history box is too narrow in vertical-order-book mode (screen of my laptop is small though). Can it be placed at the bottom in this case (for example aside "my orders" box)?

**Comment by svk31** [comment]
This issue was moved to bitshares/bitshares-ui#42
