### ISSUE TITLE
buy/sell does not calculate the price itself

### ISSUE THREAD

**Issue by btswolf** [cryptonomex/graphene-ui#776]
The buy/sell boxes do not work without a price input.
But the price should be calculated based on the Amount and Total, instead it's deleting my last input when no price is given.
![image](https://cloud.githubusercontent.com/assets/11035520/13730474/8e452c3e-e950-11e5-8d43-04587de52104.png)

**Comment by abitmore** [comment]
By now it works this way:
- if set a `price`, `amount` change will cause `total` change, `total` change will cause `amount` change
- if no `price` is set, consider `price` = 0.

**Comment by noisy** [comment]
> But the price should be calculated based on the Amount and Total, instead it's deleting my last input when no price is given.

Confirmed on version 2.0.160309

> if no price is set, consider price = 0.

price set to 0 do not make much sense. There are always 3 fields: Price, Amount, Total. They are all connected because:

Price x Amount = Total

Whenever two of three values are provided, 3rd should be automatically calculated.

**Comment by abitmore** [comment]
The actual problem is: when you already have numbers in both price and amount, when you changed total, should the UI change price or amount automatically for you? Currently the UI always change amount but never change price. 

A more detailed example: when price is empty, amount is 1, total is empty, you press the "1" key in `total` input box, you want the price change to "1"? OK, the new state is price=1, amount=1, total=1, you press the "1" key again, you want the price change to "11" or the amount change to "11"?

It's not a simple feature, if you want it be perfect, try to write a specification(detailed overall rules) first.

**Comment by svk31** [comment]
Autofilling the price based on amounts and totals doesn't make much sense to me really, and I don't think any other exchanges currently do this. Polo at least does not.. It's a very unintuitive way of determining the price so I don't know if it's worth supporting it.

**Comment by btswolf** [comment]
I just tried to place an order and I did only know how much USD I have and how much BTS I want to get. I was not able to calculate the price in my own head so I thought the GUI should be able to do that for me. I thought it would be great to have, but I also see that it is not easy to implement and probably a not much needed feature.

**Comment by svk31** [comment]
You still need to go by the current prices, so why not set a price around the current asking price, then click on your balance to enter the full amount (minus the fee if you're using that asset for the fee)?
