### ISSUE TITLE
What's wrong? Multi signature transactions do not perform?

### ISSUE THREAD

**Issue by imYao** [cryptonomex/graphene-ui#870]
![https://s19.postimg.org/qyc6msqab/What_s_wrong_with_Multi_sig_01.png](https://s19.postimg.org/qyc6msqab/What_s_wrong_with_Multi_sig_01.png)

![https://s19.postimg.org/iu42i23v7/What_s_wrong_with_Multi_sig_02.png](https://s19.postimg.org/iu42i23v7/What_s_wrong_with_Multi_sig_02.png)

**Comment by svk31** [comment]
I had a look, the operation is missing the owner approval of the account 1.2.116524 which is bbpingji.

![image](https://cloud.githubusercontent.com/assets/6890015/17882413/90d4f196-690c-11e6-993f-f7ee6c30894c.png)

That should not be the case though, so I think there must be a bug in the witness_node since bbpingji is _not_ included in the owner auths of the account.

![image](https://cloud.githubusercontent.com/assets/6890015/17882446/c595824c-690c-11e6-9d09-f54ca01b65a7.png)

**Comment by svk31** [comment]
Thanks to @xeroc the mystery has been resolved! My previous assumptions were incorrect, I forgot that the proposal object does not contain recursive required approvals, only the top level account even if it's a multi-sig account as in this case.

The actual issue was simply that the account bbpingji did not have sufficient BTS to pay the fee for the transaction! Once xeroc transfered 1 BTS to the account, the proposed transaction executed as expected.

This information isn't readily available but I'll see if I can add an indication to the UI that the account has insufficient fees.

**Comment by svk31** [comment]
Closing this and creating a new more specific issue.

**Comment by xeroc** [comment]
> The actual issue was simply that the account bbpingji did not have sufficient BTS to pay the fee for the transaction! Once xeroc transfered 1 BTS to the account, the proposed transaction executed as expected.

As a remark, after transferring the 1 BTS to the account, the proposal would not have executed automatically before reaching the expiration time at which time the network would have tried a last time to execute. Then it would have succeeded since sufficient funds were available.

In your case, I transferred 1 BTS to the account _and_ added my approval to the proposal which made the proposal re-evaluate and execute.
